// Generates the static, pre-sized WebP variants of every local banner (public/banners/**) and the manifest the app reads
// (src/lib/editorial/banner-variants.generated.ts). Local banners are served straight from /public: they never go through
// /_next/image, whose in-flight cache can leave concurrent requests for a cold entry hanging when the first client aborts
// (docs/admin/cms-v1-round3.md §2.2, scripts/repro-image-optimizer-hang.mts).
//
//   npx tsx scripts/build-banner-variants.mts        # rerun after adding or replacing a banner PNG/JPG
//
// The originals stay where they are (they remain the art masters and the fallback). Output is deterministic for the same input.
import { mkdir, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.join(process.cwd(), "public", "banners");
const OUT = path.join(process.cwd(), "src", "lib", "editorial", "banner-variants.generated.ts");
const WIDTHS = [640, 1080, 1920] as const;
const QUALITY = 80;

async function* walk(dir: string): AsyncGenerator<string> {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (/\.(png|jpe?g)$/i.test(entry.name)) yield full;
  }
}

type Variant = { w: number; h: number; src: string; bytes: number };
const manifest: Record<string, { width: number; height: number; original: number; variants: Variant[] }> = {};
let before = 0;
let after = 0;

for await (const file of walk(ROOT)) {
  const rel = "/" + path.relative(path.join(process.cwd(), "public"), file).split(path.sep).join("/");
  const image = sharp(file);
  const meta = await image.metadata();
  const original = (await stat(file)).size;
  const variants: Variant[] = [];
  for (const target of WIDTHS) {
    const w = Math.min(target, meta.width!);
    if (variants.some((v) => v.w === w)) continue; // a source narrower than the target is not upscaled
    const outFile = file.replace(/\.(png|jpe?g)$/i, `-${w}.webp`);
    const info = await sharp(file).resize({ width: w }).webp({ quality: QUALITY, effort: 5 }).toFile(outFile);
    variants.push({ w, h: info.height, src: "/" + path.relative(path.join(process.cwd(), "public"), outFile).split(path.sep).join("/"), bytes: info.size });
  }
  manifest[rel] = { width: meta.width!, height: meta.height!, original, variants };
  before += original;
  after += variants.reduce((n, v) => n + v.bytes, 0);
  console.log(`${rel}  ${meta.width}x${meta.height}  ${(original / 1024).toFixed(0)} KiB -> ${variants.map((v) => `${v.w}w ${(v.bytes / 1024).toFixed(0)} KiB`).join(", ")}`);
}

const sorted = Object.fromEntries(Object.entries(manifest).sort(([a], [b]) => (a < b ? -1 : 1)));
await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(
  OUT,
  `// GENERATED by scripts/build-banner-variants.mts — do not edit by hand.\nexport type BannerVariant = { w: number; h: number; src: string; bytes: number };\nexport const BANNER_VARIANTS: Readonly<Record<string, { width: number; height: number; original: number; variants: readonly BannerVariant[] }>> = ${JSON.stringify(sorted, null, 2)};\n`,
);
console.log(`\n${Object.keys(manifest).length} banners; originals ${(before / 1048576).toFixed(1)} MiB; all variants together ${(after / 1048576).toFixed(1)} MiB`);
