// GENERATED by scripts/build-banner-variants.mts — do not edit by hand.
export type BannerVariant = { w: number; h: number; src: string; bytes: number };
export const BANNER_VARIANTS: Readonly<Record<string, { width: number; height: number; original: number; variants: readonly BannerVariant[] }>> = {
  "/banners/sul/campaign-desktop.png": {
    "width": 1122,
    "height": 1402,
    "original": 2486196,
    "variants": [
      {
        "w": 640,
        "h": 800,
        "src": "/banners/sul/campaign-desktop-640.webp",
        "bytes": 93020
      },
      {
        "w": 1080,
        "h": 1350,
        "src": "/banners/sul/campaign-desktop-1080.webp",
        "bytes": 209272
      },
      {
        "w": 1122,
        "h": 1402,
        "src": "/banners/sul/campaign-desktop-1122.webp",
        "bytes": 219404
      }
    ]
  },
  "/banners/sul/campaign-mobile.png": {
    "width": 1122,
    "height": 1402,
    "original": 2042108,
    "variants": [
      {
        "w": 640,
        "h": 800,
        "src": "/banners/sul/campaign-mobile-640.webp",
        "bytes": 56292
      },
      {
        "w": 1080,
        "h": 1350,
        "src": "/banners/sul/campaign-mobile-1080.webp",
        "bytes": 118218
      },
      {
        "w": 1122,
        "h": 1402,
        "src": "/banners/sul/campaign-mobile-1122.webp",
        "bytes": 123328
      }
    ]
  },
  "/banners/sul/city-desktop.png": {
    "width": 1916,
    "height": 821,
    "original": 2781626,
    "variants": [
      {
        "w": 640,
        "h": 274,
        "src": "/banners/sul/city-desktop-640.webp",
        "bytes": 43106
      },
      {
        "w": 1080,
        "h": 463,
        "src": "/banners/sul/city-desktop-1080.webp",
        "bytes": 112076
      },
      {
        "w": 1916,
        "h": 821,
        "src": "/banners/sul/city-desktop-1916.webp",
        "bytes": 278580
      }
    ]
  },
  "/banners/sul/city-mobile.png": {
    "width": 1448,
    "height": 1086,
    "original": 2765315,
    "variants": [
      {
        "w": 640,
        "h": 480,
        "src": "/banners/sul/city-mobile-640.webp",
        "bytes": 77056
      },
      {
        "w": 1080,
        "h": 810,
        "src": "/banners/sul/city-mobile-1080.webp",
        "bytes": 195504
      },
      {
        "w": 1448,
        "h": 1086,
        "src": "/banners/sul/city-mobile-1448.webp",
        "bytes": 304932
      }
    ]
  },
  "/banners/sul/ddd-desktop.png": {
    "width": 1916,
    "height": 821,
    "original": 2244040,
    "variants": [
      {
        "w": 640,
        "h": 274,
        "src": "/banners/sul/ddd-desktop-640.webp",
        "bytes": 30968
      },
      {
        "w": 1080,
        "h": 463,
        "src": "/banners/sul/ddd-desktop-1080.webp",
        "bytes": 70498
      },
      {
        "w": 1916,
        "h": 821,
        "src": "/banners/sul/ddd-desktop-1916.webp",
        "bytes": 158564
      }
    ]
  },
  "/banners/sul/ddd-mobile.png": {
    "width": 1254,
    "height": 1254,
    "original": 2400987,
    "variants": [
      {
        "w": 640,
        "h": 640,
        "src": "/banners/sul/ddd-mobile-640.webp",
        "bytes": 78774
      },
      {
        "w": 1080,
        "h": 1080,
        "src": "/banners/sul/ddd-mobile-1080.webp",
        "bytes": 178128
      },
      {
        "w": 1254,
        "h": 1254,
        "src": "/banners/sul/ddd-mobile-1254.webp",
        "bytes": 218716
      }
    ]
  },
  "/banners/sul/fala-daqui-desktop.png": {
    "width": 1916,
    "height": 821,
    "original": 2080402,
    "variants": [
      {
        "w": 640,
        "h": 274,
        "src": "/banners/sul/fala-daqui-desktop-640.webp",
        "bytes": 27206
      },
      {
        "w": 1080,
        "h": 463,
        "src": "/banners/sul/fala-daqui-desktop-1080.webp",
        "bytes": 56624
      },
      {
        "w": 1916,
        "h": 821,
        "src": "/banners/sul/fala-daqui-desktop-1916.webp",
        "bytes": 121536
      }
    ]
  },
  "/banners/sul/fala-daqui-mobile.png": {
    "width": 1254,
    "height": 1254,
    "original": 2126409,
    "variants": [
      {
        "w": 640,
        "h": 640,
        "src": "/banners/sul/fala-daqui-mobile-640.webp",
        "bytes": 53178
      },
      {
        "w": 1080,
        "h": 1080,
        "src": "/banners/sul/fala-daqui-mobile-1080.webp",
        "bytes": 110910
      },
      {
        "w": 1254,
        "h": 1254,
        "src": "/banners/sul/fala-daqui-mobile-1254.webp",
        "bytes": 134934
      }
    ]
  },
  "/banners/sul/hero-desktop.png": {
    "width": 2048,
    "height": 768,
    "original": 2546117,
    "variants": [
      {
        "w": 640,
        "h": 240,
        "src": "/banners/sul/hero-desktop-640.webp",
        "bytes": 26496
      },
      {
        "w": 1080,
        "h": 405,
        "src": "/banners/sul/hero-desktop-1080.webp",
        "bytes": 69162
      },
      {
        "w": 1920,
        "h": 720,
        "src": "/banners/sul/hero-desktop-1920.webp",
        "bytes": 171966
      }
    ]
  },
  "/banners/sul/hero-mobile.png": {
    "width": 1122,
    "height": 1402,
    "original": 2455947,
    "variants": [
      {
        "w": 640,
        "h": 800,
        "src": "/banners/sul/hero-mobile-640.webp",
        "bytes": 97366
      },
      {
        "w": 1080,
        "h": 1350,
        "src": "/banners/sul/hero-mobile-1080.webp",
        "bytes": 217104
      },
      {
        "w": 1122,
        "h": 1402,
        "src": "/banners/sul/hero-mobile-1122.webp",
        "bytes": 231132
      }
    ]
  },
  "/banners/sul/state-pr.png": {
    "width": 1122,
    "height": 1402,
    "original": 2584391,
    "variants": [
      {
        "w": 640,
        "h": 800,
        "src": "/banners/sul/state-pr-640.webp",
        "bytes": 103802
      },
      {
        "w": 1080,
        "h": 1350,
        "src": "/banners/sul/state-pr-1080.webp",
        "bytes": 236816
      },
      {
        "w": 1122,
        "h": 1402,
        "src": "/banners/sul/state-pr-1122.webp",
        "bytes": 251230
      }
    ]
  },
  "/banners/sul/state-rs.png": {
    "width": 1122,
    "height": 1402,
    "original": 2584388,
    "variants": [
      {
        "w": 640,
        "h": 800,
        "src": "/banners/sul/state-rs-640.webp",
        "bytes": 97790
      },
      {
        "w": 1080,
        "h": 1350,
        "src": "/banners/sul/state-rs-1080.webp",
        "bytes": 222680
      },
      {
        "w": 1122,
        "h": 1402,
        "src": "/banners/sul/state-rs-1122.webp",
        "bytes": 240582
      }
    ]
  },
  "/banners/sul/state-sc.png": {
    "width": 1122,
    "height": 1402,
    "original": 2486196,
    "variants": [
      {
        "w": 640,
        "h": 800,
        "src": "/banners/sul/state-sc-640.webp",
        "bytes": 93020
      },
      {
        "w": 1080,
        "h": 1350,
        "src": "/banners/sul/state-sc-1080.webp",
        "bytes": 209272
      },
      {
        "w": 1122,
        "h": 1402,
        "src": "/banners/sul/state-sc-1122.webp",
        "bytes": 219404
      }
    ]
  }
};
